### ISSUE TITLE
IsPackable default

### ISSUE THREAD

**Issue by Noggog** [kzu/nugetizer#26]
One thing that caught me off guard for a while was that the default for IsPackable is `false`?  I believe without Nugetizer it's default true, so the lack of property definition means it's packed.   

I eventually figured it out and added the property everywhere, but it was initially disorienting

**Comment by kzu** [comment]
Yes, the fact that IsPackable=true by default with SDK pack makes no sense. Why would everything be packable by default??

BTW, if you provide a PackageId, the project becomes packable (IsPackable defaults to true in that case). Makes way more sense.

I think this is by design and I don't think it makes sense to follow the weird rule in SDK Pack, honestly. You end up with spurious packages for everything if you do `dotnet pack` from a solution

**Comment by kzu** [comment]
For one of the main reasons why this makes things infinitely more complicated on more realistic scenarios, checkout this thread: https://github.com/NuGet/Home/issues/3891

It's very non-trivial for them because they made everything packable by default, so the packing things you're just packing dependencies, rather than the actual project bits. This is a non-issue for nugetizer since you need to explicitly tell which projects you want packages for, and which are just assets contributed to the referencing project(s).
